name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Verify package.json up-to-date (tshy)
        shell: bash
        run: |
          # Run tshy to (re)generate package metadata based on current config
          bunx -y tshy

          # Fail if running tshy would modify the committed package.json
          if ! git diff --quiet -- package.json; then
            echo "::error file=package.json::package.json changed after running tshy. Run 'bunx tshy' locally and commit the result."
            echo "Showing diff for package.json:"
            git --no-pager diff -- package.json
            exit 1
          fi

          # Clean up build artifacts to avoid affecting subsequent lint steps
          rm -rf dist .tshy

      - name: Run CI
        run: bun run ci
